### ISSUE TITLE
Test suite failure in version 0.9.0

### ISSUE THREAD

**Issue by peti** [vincenthz/hs-asn1#12]
A complete log file of the test run is at http://hydra.nixos.org/build/16373034/nixlog/1/raw.

**Comment by peti** [comment]
Ping?

**Comment by stere0id** [comment]
Same problem here. Also works on 32bit but not 64bit linux.

**Comment by trofi** [comment]
Encountered it as well. The problem here suggests it's a couple of issues
- issue with Int size issue in year definition
- issue with test that passes out-of-range values to TimeUTC (cound be an Int overflow side effect), comment says it in 1950-2050 range

```
got:      Right [ASN1Time TimeUTC (... {dateYear = 2011, ...
expected: Right [ASN1Time TimeUTC (...{dateYear = 1911, ...
```
```
*Data.ASN1.Types> :info Date      
data Date
  = Date {dateYear :: {-# UNPACK #-}Int,
          dateMonth :: !Month,
          dateDay :: {-# UNPACK #-}Int}
        -- Defined in ‘Data.Hourglass.Types’
```

**Comment by trofi** [comment]
Another weird discrepancy comes from `normalizeDate` function:

```
normalizeDate: (Date {dateYear = 2046, dateMonth = May, dateDay = 1},"->",Date {dateYear = 1910, dateMonth = March, dateDay = 25})
```

**Comment by vincenthz** [comment]
I've hacked the test to not generate offending dates; this doesn't warrant more fixing I think, 32 bit time_t shouldn't be acceptable anymore really.
