### ISSUE TITLE
decodeASN1Repr failed for a certificate on Windows

### ISSUE THREAD

**Issue by yogeshsajanikar** [vincenthz/hs-asn1#13]
Data.ASN1.Encoding.decodeASN1Repr failed while processing a certificate issued by "SAP Trust Community". 

The error is ***'TypeDecodingFailed "time format invalid for TimeUTC : cannot convert string 0007181000Z***

I suspected it to be same as - 
[https://github.com/elm-lang/elm-reactor/issues/98]

**Comment by romankras** [comment]
Yogesh thank you for your findings, I have the same certificate :)

**Comment by habbler** [comment]
To get around this I patched module System.X509.Win32

 in getSystemCertificateStore

                    case ecert of
                        Left _     -> loop st r
                        Right cert -> (cert :) <$> (loop st r)
                    `catch` \(_ :: ASN1Error)-> loop st r

Better than just dying. Ignores all certificates that have an ANS1Error

**Comment by vincenthz** [comment]
ultimately I don't think it's a bug in the ASN1 library, not sure what this time value could represent. If anyone knows what the encoding for this time value is please speak up.

**Comment by habbler** [comment]
If you look at http://luca.ntop.org/Teaching/Appunti/asn1.html under section "5.17 UTCTime"
You can see that certificate validity times are allowed to be in the form

YYMMDDhhmmZ
As such the above is a valid time (2000-07-18 10:00 )

**Comment by vincenthz** [comment]
ah that make more sense, somehow I assumed generalized time and that didn't make sense. hopefully I fixed the format issue now. Thanks
