### ISSUE TITLE
Export parser?

### ISSUE THREAD

**Issue by Gabriel439** [vincenthz/hs-asn1#16]
It looks like this library rolls its own parser under the hood in the internal `Data.ASN1.Get` module that looks the same as the parser in the `cereal` library.  Would it be possible to reuse `cereal` and export your parser so that this can be embedded within a larger parser?

**Comment by vincenthz** [comment]
it's very similar but it has an extra position of the stream. As to using this parser directly in another parser, while it would be useful, it's very easy to abuse the parser since it doesn't have any limits.
