### ISSUE TITLE
Segmentation fault on invalid input

### ISSUE THREAD

**Issue by hreinhardt** [vincenthz/hs-asn1#17]
Running the following program

``` haskell
import qualified Data.ByteString as B
import Data.ASN1.Encoding
import Data.ASN1.BinaryEncoding

main = do
    f <- B.readFile "data.txt"
    print $ decodeASN1Repr' DER f
```

on the attached file ([data.txt](https://github.com/vincenthz/hs-asn1/files/297497/data.txt)) produces a segmentation fault on GHC 7.8.2 and 8.0.1 on Windows.

**Comment by enolan** [comment]
Crashes on Linux too. I used `afl-tmin` and got a much smaller [testcase](https://github.com/vincenthz/hs-asn1/files/298703/aflreduced.txt).

**Comment by enolan** [comment]
It's an integer overflow problem. I'll have a PR soon.

**Comment by vincenthz** [comment]
I added 8a8d34b8141819dc53d0c6bb9c07f5dce6ac175d to make the parser solid, it doesn't actually require such a fine tuning anyway, but re-reading the source after many years, I don't understand why ensure is not doing its expected job. is there some fundamental integer overflow somewhere else than the ASN1 parser ? it seems to do the job to at least fall the parsing with a parsing error, not a segfault !

@enolan: please let me know if you want to add anything to the repo, I'll cut a release ASAP provided it's all working (confirmation of doing the right thing is good too)

**Comment by vincenthz** [comment]
I think this has been fixed now
