### ISSUE TITLE
How to represent CHOICE?

### ISSUE THREAD

**Issue by libscott** [vincenthz/hs-asn1#21]
[This page](http://luca.ntop.org/Teaching/Appunti/asn1.html) says that CHOICE does not have a [Tag](https://hackage.haskell.org/package/asn1-types-0.3.2/docs/Data-ASN1-Types.html#t:ASN1Tag), but it's not obvious how to encode such an object inside `ASN1`. Also, trying to encode an `End Sequence` on its own gives an error.

Could you give some indication how to encode an ASN1 CHOICE value using this library?

**Comment by libscott** [comment]
I think I've answered my own question, looks like CHOICE can be encoded as:

`choice choiceID data` = encodeASN1 DER [Other Context choiceID data]`

Is this the intention? If so, think it would be worth documenting somewhere?

**Comment by vincenthz** [comment]
There's no specific encoding for choice because it's just a way to express an alternative at the *grammar* level. If you were to expect a choice of either an Int or a Bitmap then it means at the representation level that you have something like:

```
nextParser (x:xs) = 
case x of
   AsnInt .. -> ..
   AsnBitString .. -> ...
```
