### ISSUE TITLE
asn1-types-0.9.4 build error on Hackage GHC 8.2.2 doc build

### ISSUE THREAD

**Issue by YoEight** [vincenthz/hs-asn1#25]
Greetings,

```
Building library for asn1-parse-0.9.4..
[1 of 1] Compiling Data.ASN1.Parse  ( Data/ASN1/Parse.hs, dist/dist-sandbox-9df84abc/build/Data/ASN1/Parse.o )

Data/ASN1/Parse.hs:28:1: error:
    Could not find module ‘Data.ASN1.Types’
    There are files missing in the ‘asn1-types-0.3.2’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.
   |
28 | import Data.ASN1.Types
   | ^^^^^^^^^^^^^^^^^^^^^^

Data/ASN1/Parse.hs:29:1: error:
    Could not find module ‘Data.ASN1.Stream’
    There are files missing in the ‘asn1-encoding-0.9.5’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.
   |
29 | import Data.ASN1.Stream
   | ^^^^^^^^^^^^^^^^^^^^^^^
cabal: Leaving directory '/tmp/cabal-tmp-1246/asn1-parse-0.9.4'
```

Thanks for your time.

**Comment by vincenthz** [comment]
That doesn't looks like an issue with asn1 but with the builder. what exactly happens here ?

**Comment by YoEight** [comment]
I don't know much about it but here's my hackage documentation build job: https://hackage.haskell.org/package/eventstore-1.0.0/reports/1

**Comment by vincenthz** [comment]
The further error in the log and that asn1 has been building in doc for the last 3 years, makes me think it's not a problem of asn1 but some unspecified doc builder issue probably related to the recent switch to 8.2:

```
/usr/bin/ld.gold: error: cannot find -lHStransformers-compat-0.5.1.4-8ROpHfTW2Zp5hyE7gQe9fh-ghc8.2.2
```

**Comment by vincenthz** [comment]
Closing for now, if you find evidence that asn1 is missing something/doing something wrong, please re-open

**Comment by YoEight** [comment]
Sound fair to me. I just stumbled on that error and I thought it would be helpful to report. Stackage documentation is building fine so I think you got a valid point here.

**Comment by vincenthz** [comment]
yeah it is helpful to report errors, just in cases. It's tricky when you look at a black box output to see what actually happen.

**Comment by gbaz** [comment]
Yes, this was an issue with the docbuilder (occasioned by kicking it over to 8.2.2), now fixed. We cleared rebuilds for most things affected but somehow missed eventstore -- docs have now built for that too.
