### ISSUE TITLE
fix compilation with GHC 8.8.1 / MonadFail

### ISSUE THREAD

**Issue by mgmeier** [vincenthz/hs-asn1#33]
Currently, asn1-data and asn1-encoding don't compile, since the define `fail` for a `Monad`; files affected are:
```
data/Data/ASN1/Get.hs:108
encoding/Data/ASN1/Get.hs:106
```

The intuitive (to me) way to fix this would be using a conditional compilation similar to what you've done already in parse/Data/ASN1/Parse.hs:63:
```
#if MIN_VERSION_base(4,9,0)
instance MonadFail ParseASN1 where
    fail = throwParseError
#endif
```
by checking against GHC 8.8.1 base version, so that definitions remain unchanged for earlier base versions. In case you agree, I could prepare a PR.

**Comment by DanBurton** [comment]
Bump. Would appreciate a release compatible w/ ghc 8.8.1

**Comment by nbouscal** [comment]
@vincenthz Any update on this?
