### ISSUE TITLE
UTF-8 encoding broken due to last byte of a multi-byte character always null

### ISSUE THREAD

**Issue by moll** [vincenthz/hs-asn1#35]
Hey,

Thanks for maintaining these ASN.1 libs! If I'm not mistaken, the UTF-8 encoding implementation in https://hackage.haskell.org/package/asn1-types-0.3.3/docs/src/Data.ASN1.Types.String.html#local-6989586621679034993 is broken due to the last byte always being set null — `0xc0 & 0x3f = 0`. I presume you meant to bitwise-or it with 0x80 instead to have the first two bits be `10`.

It's easy to reproduce with my surname: `asn1CharacterToString ("Möll" :: ASN1CharacterString)`

```
Just "M*** Exception: continuation bytes invalid
CallStack (from HasCallStack):
  error, called at ./Data/ASN1/Types/String.hs:109:34 in asn1-types-0.3.3-681f1a1bec95ecc832958e8497db7f3872872f9a24538c763fb4706942450148:Data.ASN1.Types.String
```

Cheers

**Comment by vincenthz** [comment]
thanks @moll !

**Comment by moll** [comment]
Thank you, too!
