### ISSUE TITLE
asn1-encoding: Support bytestring-0.11

### ISSUE THREAD

**Issue by sjakobi** [vincenthz/hs-asn1#42]
The latest version and revision of [`asn1-encoding`](http://hackage.haskell.org/package/asn1-encoding) requires `bytestring < 0.11`. It would be nice if this constraint could be relaxed.

**Comment by sjakobi** [comment]
Ping @vincenthz! :)

**Comment by sjakobi** [comment]
FWIW I've tested locally that

```
$ cabal test -O0 --constraint 'bytestring>=0.11'
```

passes and produces no `bytestring`-related warnings.

**Comment by vincenthz** [comment]
Please see with hackage maintainers, they have introduce this spurious revision, the source repository doesn't have this constraint
http://hackage.haskell.org/package/asn1-encoding-0.9.6/revisions/

**Comment by bergmark** [comment]
Sorry about this @vincenthz. I wasn't able to find any information on why this upper bound was added so I reverted it.
